# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings - Accessible via {{ site.myvariable }}.
title: Ana María Martínez Gómez
description: A longer description of what your site is about, e.g., "Where I blog about Jekyll and other awesome things"
url: "http://anamaria.martinezgomez.name"
author: Ana María Martínez Gómez

# Build settings
markdown: kramdown

plugins:
  - jemoji
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
