# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings - Accessible via {{ site.myvariable }}.
title: "Ana María Martínez Gómez"
description: "Ana María Martínez Gómez personal page and blog"
url: "http://anamaria.martinezgomez.name"
author: "Ana María Martínez Gómez"

# Build settings
markdown: kramdown
timezone: Europe/Berlin

plugins:
  - jemoji
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
